### ISSUE TITLE
Problems with Dragonfly TempObject

### ISSUE THREAD

**Issue by charlesdeb** [romanbsd/heroku-deflater#15]
I was getting the error:

```
can't read from tempfile as TempObject has been closed
```

in my heroku logs, and no images were being served in my rails application. More details can be found at the trail here https://github.com/markevans/dragonfly/issues/250#issuecomment-32595637.

It seems like I had problems with heroku-deflater middleware closing elements in a request body if they are images since it makes little sense to try and compress them further. However, the Dragonfly gem (I guess) requires these images to not be closed so that it can do further image processing (resizing etc) on them.

As I can't easily do without dragonfly (it is very much part of RefineryCMS which I am using) my workaround right now is just to not to use Heroku-deflater.

Gems I am using are refinerycms 2.1.1, dragonfly 0.9.15, rails 3.2.15 under Ruby 2.0, and I was using heroku-deflater 0.5.3 before I removed it.

It would be great to have this deflation back again but as I don't fully understand how middleware actually works (let alone dragonfly), I doubt I could submit a working patch.

**Comment by harmoney-justins** [comment]
Hi @romanbsd 

So i've upgraded to 0.5.3 because of that deadlock issue in heroku, now dragonfly can't work too.

Can't seem to win here...

**Comment by gfx** [comment]
I've got exactly the same issue as @charlesdeb.

Please don't close body in rack middlewares because it in use.

i.e. https://github.com/romanbsd/heroku-deflater/blob/v0.6.3/lib/heroku-deflater/skip_binary.rb#L32
