### ISSUE TITLE
Content-Length header is removed

### ISSUE THREAD

**Issue by Hungor** [romanbsd/heroku-deflater#18]
As title, it cause problem for e.g. Internet Explorer.

**Comment by romanbsd** [comment]
If using inside rails, it should be re-added, I believe. If used outside rails, use the Rack::ContentLength middleware.

**Comment by Hungor** [comment]
I have tried different solutions, even writing my own middleware without success.
Then I have found out, that the error was occured by Unicorn. I changed the web server to Puma, the problem is resolved.
