### ISSUE TITLE
Syntax Error with 0.6.0 and Rails 4.2.4

### ISSUE THREAD

**Issue by babgyy** [romanbsd/heroku-deflater#22]
Hi, 
I have just encountered an error while using version 0.6.0 and Rails 4.2.4
I have solved my problem by downgrading to 0.5.3, however I wanted to let you know. [Even though I am not sure if there is actually a problem, or if I made a mistake in my configuration.]

I reproduced the issue by creating a new Rails project, added Heroku Deflater gem v0.6.0 and running >bundle install then >rails s 
See extract below:
https://gist.github.com/babgyy/366d8a3362aee8315a2a

Thanks for the gem !
Best regards
Lucas

**Comment by komerbach** [comment]
Error also appears with Rails 3.2.13

**Comment by romanbsd** [comment]
try to update to 0.6.1, it should have been fixed.

**Comment by babgyy** [comment]
Fixed. Thanks

**Comment by michaelschmitz** [comment]
Hi. I have the same issue even with 0.6.1. and set the version to gem 'heroku-deflater', '0.5.3 ', :group => :production, which helps. I don't think it has been fixed. Rails 4.2.3. See SO discussion here: http://stackoverflow.com/questions/33495595/passenger-startup-failure-on-heroku-cache-control/33502160#33502160

**Comment by romanbsd** [comment]
Hopefully fixed in 0.6.2. This is what happens when you're too busy to actually read the code in the PR :)
