### ISSUE TITLE
Issue with rails 5 API only setup

### ISSUE THREAD

**Issue by lokenmakwana** [romanbsd/heroku-deflater#29]
I want to use heroku-deflater to gzip output of my API only app but It fails with following error

```
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x000000042682a8>
Did you mean?  asset_host
/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.1/lib/rails/railtie/configuration.rb:95:in `method_missing'
```

workaround is to require 'sprockets/railtie' but there should be option to skip that

**Comment by romanbsd** [comment]
Unfortunately currently I don't have time to fix this. But if it's an API only, perhaps you don't need this gem. Just add Rack::Deflater to your rack stack.

**Comment by oyeanuj** [comment]
@lokenmakwana Where did you end up this? Did you fix this issue or just use Rack::Deflater?

**Comment by oyeanuj** [comment]
@romanbsd Would you still recommend just using Rack::Deflater with an API-only app or is the original issue fixed here?
