### ISSUE TITLE
Rack::Deflater already has this functionality?

### ISSUE THREAD

**Issue by jjb** [romanbsd/heroku-deflater#33]
As I was writing #32 I had dejavu and did some digging, and remembered that since, I believe, rack 1.6, Rack::Deflater already has the ability to not compress images. Here's the PR: https://github.com/rack/rack/pull/457

So:

```ruby
module YourApp
  class Application < Rails::Application
    config.middleware.use Rack::Deflater, include: Rack::Mime::MIME_TYPES.select{|k,v| v =~ /text|json|javascript/ }.values.uniq
  end
end
```

Just wanted to point that out in case it relieves the maintainers of heroku-deflater some burden :)

**Comment by david-a-wheeler** [comment]
I do not think that Rack::Deflator can do this:

> Before serving a file from disk to a gzip-enabled client, it will look for a precompressed file in the same location that ends in ".gz". The purpose is to avoid compressing the same file each time it is requested.

**Comment by jjb** [comment]
Oh whoops, true. But rails does that (see #32).

So maybe heroku-deflater can be changed to leverage rack-deflater's capabilities but still serve precompiled gziped files, and be useful for non-rails rack projects.

**Comment by jjb** [comment]
made #37, closing
